[package]
name = "easya"
version = "0.1.0"
authors = ["dwij patel <saurabh.sachit39@gmail.com>"]
edition = "2018"
feature="process"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
