[package]
name = "get_output"
version = "0.1.0"
authors = ["boredalchemist <harsh4444.hf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cmd_lib = "0.7.8"
rand = "0.7.3"
printpdf = ""
